

###
GET http://localhost:8080/engine-rest/process-definition

###
# curl -H "Content-Type: application/json" -X POST -d '{"variables": {"amount": {"value":555,"type":"integer"}, "item": {"value":"item-xyz"} } }' http://localhost:8080/engine-rest/process-definition/key/payment-retrieval/start
POST http://localhost:8080/engine-rest/process-definition/key/Payment-Retrieval/start
Content-Type: application/json

{
  "variables": {
    "amount": {
      "value": 555,
      "type": "integer"
    },
    "item": {
      "value": "item-xyz"
    }
  }
}

